### ISSUE TITLE
Is it possible to use `cargo-check`?

### ISSUE THREAD

**Issue by zonyitoo** [oschwald/SublimeLinter-contrib-rustc#18] opened 2015-07-21 02:43 UTC
https://github.com/rsolomo/cargo-check

Cargo check is a wrapper of `cargo rustc -- -Zno-trans`

**Comment by oschwald** [comment] 2015-07-21 02:56
It seems like we could just change our cargo call as appropriate rather than using `cargo-check`. However, testing it locally, I am having some issues building a module that builds fine with `cargo build`.

I probably won't have time in the near future to dig into this further, but a working PR would likely get merged.

**Comment by zonyitoo** [comment] 2015-07-21 03:10
`cargo rustc` requires to provide crate name or bin name via `--lib` or `--bin`, so this plugin may have to change a little bit. I tested it locally, it seems that all works well in my project.

**Comment by pzol** [comment] 2015-07-29 04:37
+1

**Comment by dginev** [comment] 2015-10-28 01:13
+1

**Comment by oschwald** [comment] 2015-10-28 01:31
As of several months ago, this linter [uses `-Zno-trans`](https://github.com/oschwald/SublimeLinter-contrib-rustc/commit/fc04d7e4bdfec388a10ab24d542e429f2bb622e5). As far as I know, using `cargo-check` would not provide any additional benefit.

**Comment by dginev** [comment] 2015-10-28 01:42
I should have specified I meant +1 to this comment:
> cargo rustc requires to provide crate name or bin name via --lib or --bin, so this plugin may have to change a little bit. I tested it locally, it seems that all works well in my project.

I had to fork the plugin and manually add ```--lib``` to verify it still works as intended for a Rust library, just get it to work again and it seems to behave exactly as expected.

There should be a check that adds ```--lib``` or ```-bin NAME``` to the ```cargo rustc``` call. Maybe simply allowing the ```args``` setting to be used in that call is enough, users can specify the flag on their own.

**Comment by oschwald** [comment] 2015-10-28 01:53
Ah, that makes sense. Adding the ability to pass arguments through sounds good.

**Comment by oschwald** [comment] 2015-12-11 03:30
This now supports `cargo check` with Rust 1.5. `cargo-check` must be installed and `use-cargo-check` must be enabled.

**Closed by oschwald** 2015-12-11 03:30 UTC
